services:
  flask-api:
    build: ./api
    container_name: flask_backend
    ports:
      - "5000:5000"

  shiny-ui:
    build: ./shiny_app
    container_name: shiny_frontend
    ports:
      - "8000:8000"
    environment:
      - API_URL=http://flask-api:5000
    depends_on:
      - flask-api